ministryofjustice/hmpps-welcome-people-into-prison-ui

helm_deploy/values-dev.yaml

DCS-1099 Setting secret name

---

integration_tests/integration/confirmAddedToRoll.spec.ts
integration_tests/mockApis/welcome.ts
package-lock.json
server/@types/welcome/index.d.ts
server/data/welcomeClient.test.ts
server/routes/confirmAddedToRollController.test.ts
server/views/pages/confirmAddedToRoll.njk

longDescription changed to description (refer to the story for detail)

DCS-1255: move to do prison lookup using prison registry

---

server/middleware/validation/imprisonmentStatusesValidation.test.ts
server/middleware/validation/imprisonmentStatusesValidation.ts
server/middleware/validation/movementReasonsValidation.test.ts
server/middleware/validation/movementReasonsValidation.ts
server/routes/imprisonmentStatusesController.test.ts
server/routes/movementReasonsController.test.ts
server/routes/movementReasonsController.ts
server/utils/nunjucksSetup.ts
server/views/pages/imprisonmentStatus.njk
server/views/pages/movementReason.njk
server/views/partials/layout.njk

Introduced new Nunjucks filters for radio button loops and error message display.

DCS-1263 view templates refactored to use nunjucks components.

---

server/data/welcomeClient.test.ts
server/data/welcomeClient.ts
server/routes/checkTransferController.test.ts
server/routes/checkTransferController.ts
server/routes/index.ts
server/services/index.ts
server/services/transfersService.test.ts
server/services/transfersService.ts

all transfer calls will eventually be moved into transferService

DCS-1277  get individual transfer from welcome-api

---

server/routes/checkTransferController.test.ts
server/routes/checkTransferController.ts
server/routes/confirmTransferAddedToRollController.test.ts
server/routes/confirmTransferAddedToRollController.ts
server/routes/index.ts
server/services/transfersService.ts
server/views/pages/confirmTransferAddedToRoll.njk
server/views/partials/layout.njk

Integration test to be added in another ticket
view looks like this

DCS-1280 add controller, service and view for prison transfer

---

integration_tests/integration/checkTransfer.spec.ts
integration_tests/integration/confirmTransferAddedToRoll.spec.ts
integration_tests/mockApis/welcome.ts
integration_tests/pages/checkTransfer.ts
integration_tests/pages/confirmTransferAddedToRoll.ts
integration_tests/plugins/index.ts
server/routes/confirmTransferAddedToRollController.test.ts
server/routes/confirmTransferAddedToRollController.ts
server/routes/index.ts

Note the text content of pages has been tested in the unit tests already

DCS-1280 integration tests for prison transfer

---

feature.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/app.ts
server/config.ts
server/middleware/caseloadCheckMiddleware.test.ts
server/middleware/caseloadCheckMiddleware.ts
server/routes/testutils/requestTestUtils.ts

DCS-1102-wpip-ui prevent access if user does not have Nottingham 

---

feature.env
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
server/config.ts
server/utils/nunjucksSetup.ts
server/views/home.njk

This is just returning canned data

DCS-1358 Hiding temporary absences in preprod and prod

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

This reverts commit c1c39732c139bc13ab638d40c6883aa761260538.

Revert "DCS-1358 Enabling confirm of arrival in prod (#76)"

---

integration_tests/integration/checkTemporaryAbsence.spec.ts
integration_tests/integration/checkTransfer.spec.ts
integration_tests/integration/confirmTransferAddedToRoll.spec.ts
integration_tests/mockApis/welcome.ts
integration_tests/pages/checkTemporaryAbsence.ts
integration_tests/pages/confirmTemporaryAbsenceAddedToRoll.ts
integration_tests/pages/temporaryAbsences.ts
integration_tests/plugins/index.ts
server/data/welcomeClient.test.ts
server/data/welcomeClient.ts
server/routes/checkTemporaryAbsenceController.test.ts
server/routes/checkTemporaryAbsenceController.ts
server/routes/confirmTemporaryAbsenceAddedToRollController.ts
server/routes/index.ts
server/routes/temporaryAbsencesController.test.ts
server/services/temporaryAbsencesService.test.ts
server/services/temporaryAbsencesService.ts
server/utils/nunjucksSetup.ts
server/views/home.njk
server/views/pages/checkTemporaryAbsence.njk
server/views/pages/confirmTemporaryAbsenceAddedToRoll.njk
server/views/pages/temporaryAbsences.njk
server/views/partials/temporaryAbsenceCardMacro.njk

Note: Contents of confirmTemporaryAbsenceAddedToRoll.njk view page to be added in a future ticket, draft view page included as part of this PR to play out navigation from temporary absence check page.

DCS-1379 updated returning from temporary absence url

---

server/routes/bookedtoday/arrivals/index.ts
server/routes/bookedtoday/arrivals/searchforexisting/index.ts
server/routes/bookedtoday/arrivals/searchforexisting/searchForExistingRecordController.test.ts
server/routes/bookedtoday/arrivals/searchforexisting/searchForExistingRecordController.ts
server/views/pages/bookedtoday/arrivals/confirmArrival.njk
server/views/pages/bookedtoday/arrivals/searchForExistingRecord/searchForExistingRecord.njk

DCS-1348 Adding search for existing record page

---

server/routes/bookedtoday/arrivals/searchforexisting/changeDateOfBirthController.test.ts
server/routes/bookedtoday/arrivals/searchforexisting/changeDateOfBirthController.ts
server/routes/bookedtoday/arrivals/searchforexisting/changeNameController.test.ts
server/routes/bookedtoday/arrivals/searchforexisting/changeNameController.ts
server/routes/bookedtoday/arrivals/searchforexisting/changePncNumberController.test.ts
server/routes/bookedtoday/arrivals/searchforexisting/changePncNumberController.ts
server/routes/bookedtoday/arrivals/searchforexisting/changePrisonNumberController.test.ts
server/routes/bookedtoday/arrivals/searchforexisting/changePrisonNumberController.ts
server/routes/bookedtoday/arrivals/searchforexisting/index.ts
server/views/pages/bookedtoday/arrivals/searchForExistingRecord/changeDateOfBirth.njk
server/views/pages/bookedtoday/arrivals/searchForExistingRecord/changeName.njk
server/views/pages/bookedtoday/arrivals/searchForExistingRecord/changePncNumber.njk
server/views/pages/bookedtoday/arrivals/searchForExistingRecord/changePrisonNumber.njk

Will add fields in a follow up

DCS-1348 Adding change pages

---

integration_tests/integration/bookedtoday/arrivals/checkAnswers.spec.ts
integration_tests/integration/bookedtoday/arrivals/choosePrisoner.spec.ts
integration_tests/integration/bookedtoday/arrivals/confirmAddedToRoll.spec.ts
integration_tests/integration/bookedtoday/arrivals/confirmArrival.spec.ts
integration_tests/integration/bookedtoday/arrivals/courtreturns/checkCourtReturn.spec.ts
integration_tests/integration/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.spec.ts
integration_tests/integration/bookedtoday/arrivals/imprisonmentStatus.spec.ts
integration_tests/integration/bookedtoday/arrivals/movementReasons.spec.ts
integration_tests/integration/bookedtoday/arrivals/sex.spec.ts
integration_tests/integration/bookedtoday/transfers/checkTransfer.spec.ts
integration_tests/integration/bookedtoday/transfers/confirmTransferAddedToRoll.spec.ts
integration_tests/integration/temporaryabsences/checkTemporaryAbsence.spec.ts
integration_tests/integration/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.spec.ts
integration_tests/integration/temporaryabsences/temporaryAbsences.spec.ts
server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.test.ts
server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.ts
server/routes/bookedtoday/arrivals/courtreturns/confirmCourtReturnController.test.ts
server/routes/bookedtoday/arrivals/courtreturns/confirmCourtReturnController.ts
server/routes/bookedtoday/arrivals/courtreturns/index.ts
server/routes/bookedtoday/arrivals/index.ts
server/routes/bookedtoday/choosePrisonerController.test.ts
server/views/pages/bookedtoday/arrivals/courtreturns/checkCourtReturn.njk
server/views/pages/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.njk
server/views/pages/bookedtoday/choosePrisoner.njk
server/views/partials/expectedArrivalCardMacro.njk

This also restructures the specs into a structure that matches the routes: 
<kbd>
</kbd>
(Includes moving courtreturns into own separate subpackage)

DCS-1348 Tidying up macros

---

server/routes/temporaryabsences/temporaryAbsencesController.test.ts
server/views/pages/temporaryabsences/temporaryAbsences.njk
server/views/partials/temporaryAbsenceCardMacro.njk

**display when no absences**
**display when multiple absences**

DCS-1410 display message if no temporary absences

---

helm_deploy/values-prod.yaml

This reverts commit 747494d4db6c86a806ceb1bebd84f8e05f7edf1e.

Revert "DCS-1431 Enabling testing in prod (#126)"

---

helm_deploy/values-prod.yaml

FOR ENABLING NOTTINGHAM
This reverts commit ee598583ac9a24877cf922aece4a19d6fffb9fb2.

Revert "Revert "DCS-1431 Enabling testing in prod (#126)" (#127)"

---

helm_deploy/values-prod.yaml

This reverts commit 845e7b72a681494829015288ba8768d76eafbc28.

Revert "DCS-1431 disable testing in nottingham (#131)"

---

helm_deploy/values-prod.yaml

This reverts commit d199ca997730d28899cf844c7459c1861476c96a.

Revert "DCS-1431 disabling nottingham testing in prod (#134)"

---

integration_tests/integration/bookedtoday/arrivals/existingRecord.spec.ts
integration_tests/integration/bookedtoday/choosePrisoner.spec.ts
integration_tests/integration/temporaryabsences/temporaryAbsences.spec.ts
integration_tests/mockApis/welcome.ts
server/data/welcomeClient.ts
server/routes/index.ts
server/routes/prisonerController.test.ts
server/views/pages/bookedtoday/arrivals/confirmArrival.njk
server/views/pages/bookedtoday/arrivals/courtreturns/checkCourtReturn.njk
server/views/pages/bookedtoday/transfers/checkTransfer.njk
server/views/pages/temporaryabsences/checkTemporaryAbsence.njk
server/views/partials/expectedArrivalCardMacro.njk
server/views/partials/temporaryAbsenceCardMacro.njk

Also move to new images endpoint

DCS-1460 fix image display when match with PNC only

---

integration_tests/integration/bookedtoday/arrivals/matchingRecords/possibleRecordsFound.spec.ts
integration_tests/pages/bookedtoday/arrivals/matchingRecords/possibleRecordsFound.ts
server/routes/bookedtoday/arrivals/matchingRecords/possibleRecordsFoundController.ts

refactored integration tests and used new state object when there are potentially multiple records matching the new arrival

DCS 1350 multiple matches refactor

---

server/routes/bookedtoday/choosePrisonerController.test.ts
server/routes/bookedtoday/index.ts

Not wrapping this in async handlers causes the process to terminate

DCS-1477 Handling rejected promises

---

integration_tests/integration/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.spec.ts
server/routes/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFoundController.ts
server/views/pages/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.njk

Also showing PNC and Prison number of arrival

DCS-1350 Fixing display of prisoner image.

---

server/views/pages/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecord.njk

DCS-1423 removed text to match prototype

---

integration_tests/integration/bookedtoday/unexpectedArrivals/searchForExistingRecord.spec.ts
integration_tests/pages/bookedtoday/unexpectedArrivals/multipleRecordsFound.ts
integration_tests/pages/bookedtoday/unexpectedArrivals/noRecordsFound.ts
integration_tests/pages/bookedtoday/unexpectedArrivals/singleRecordFound.ts

change file names as suggested in previous PR and add integration tests for validation messages

DCS-1467, integration tests

---

integration_tests/integration/bookedtoday/unexpectedArrivals/multipleMatchingRecordsFound.spec.ts
server/views/pages/unexpectedArrivals/multipleExistingRecordsFound.njk

DCS-1467 change page targeted by link

---

server/views/pages/unexpectedArrivals/singleExistingRecordFound.njk

link to go to new search rather than create record.
see /v13/confirm-arrival/new-arrival/record-found of the prototype

DCS-1539 change link target

---

server/views/pages/unexpectedArrivals/singleExistingRecordFound.njk

DCS-1468 add full stop to end of link text

---

integration_tests/integration/bookedtoday/arrivals/courtreturns/courtReturn.spec.ts
integration_tests/pages/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.ts
server/views/pages/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.njk

DCS-1478 updated content on court return confirmation page

---

integration_tests/integration/bookedtoday/transfers/transfer.spec.ts
integration_tests/pages/bookedtoday/transfers/confirmTransferAddedToRoll.ts
server/views/pages/bookedtoday/transfers/confirmTransferAddedToRoll.njk

DCS-1478 content update on transfer confirmation page

---

integration_tests/integration/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.spec.ts
integration_tests/pages/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.ts
server/views/pages/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.njk

DCS-1478 content update on temporary absence confirmation page

---

server/routes/bookedtoday/arrivals/validation/dateOfBirthValidation.test.ts
server/routes/bookedtoday/arrivals/validation/dateOfBirthValidation.ts
server/routes/bookedtoday/unexpectedArrivals/validation/SearchForExistingRecordsDateOfBirthValidation.test.ts
server/routes/bookedtoday/unexpectedArrivals/validation/SearchForExistingRecordsDateOfBirthValidation.ts
server/utils/utils.test.ts
server/utils/utils.ts

Past DOB validation added to make sure that a user doesn't accidentally input a date of birth which is in the future in error:

DCS-1703 future dob validation

---

server/utils/utils.test.ts
server/utils/utils.ts

Handle today's date for dob validation:
Screen shot taken on 05/07/2022

DCS-1703 handle today date input for dob validation

---

jobs/eventsJob.ts
jobs/eventsPusher.ts
server/data/welcomeClient.ts

We assume the < 2 was incorrectly referring to a header but will keep an eye out for anonymallys
Also fixing job hanging on error due to not closing redis connection
Finally, fixing end point

DCS-1720 Fixing pushing job

---

integration_tests/pages/bodyscan/bodyScanConfirmation.ts
server/views/pages/bodyscans/scanConfirmation.njk

DCS-1789: ♻️ Update return url for body scan confirmation add case notes journey

---

integration_tests/integration/bookedtoday/choosePrisoner.cy.ts
server/routes/bookedtoday/arrivals/confirmArrival/startConfirmationController.test.ts
server/routes/bookedtoday/choosePrisonerController.test.ts
server/routes/bookedtoday/choosePrisonerController.ts
server/services/matchTypeDecorator.test.ts
server/services/matchTypeDecorator.ts
server/views/partials/expectedArrivalCardMacro.njk

Removing special handling of active prisoners from PCS
Also tidying up court return logic

DCS-1668 Updating redirect logic

---

integration_tests/integration/bookedtoday/choosePrisoner.cy.ts
integration_tests/mockApis/responses/expectedArrivals.ts
server/services/matchTypeDecorator.test.ts
server/services/matchTypeDecorator.ts

This matches the logic we use when doing the redirects

DCS-1851 Deriving court returns by using nomis info

---

server/views/pages/bookedtoday/arrivals/searchforexisting/noExistingRecordsFound.njk

*Changed on no existing records found page

DCS-1831-refactor-search-again-link

---

package-lock.json

DCS-1892: 🤖 Fix Security Vulnerabilities

DCS-1892: 🤖 Fix Security Vulnerabilities

---

server/data/__testutils/mocks.ts
server/data/index.ts
server/data/lockManager.test.ts
server/data/lockManager.ts
server/middleware/doubleClickPreventionMiddleware.test.ts
server/middleware/doubleClickPreventionMiddleware.ts
server/routes/__testutils/requestTestUtils.ts
server/routes/bookedtoday/arrivals/confirmArrival/checkAnswersController.test.ts
server/routes/bookedtoday/arrivals/confirmArrival/checkAnswersController.ts
server/routes/bookedtoday/arrivals/confirmArrival/index.ts
server/services/index.ts
server/views/pages/bookedtoday/arrivals/confirmArrival/checkAnswers.njk
server/views/pages/bookedtoday/arrivals/confirmArrival/checkAnswersForCreateNewRecord.njk

To address issue with users somehow by passing the standard govuk frontend double click prevention support

DCS-1967 Adding lock mechanism to prevent double click

---

package-lock.json

related to 
_Found vulnerable advisory paths:
GHSA-9c47-m6qq-7p4h|json5
Failed security audit due to high vulnerabilities.
Vulnerable advisories are:
https://github.com/advisories/GHSA-9c47-m6qq-7p4h_

DCS-1985 dependencies updated

---

assets/sass/application-ie8.sass
assets/sass/application.sass
assets/sass/components/_summary-card.scss
server/routes/bookedtoday/index.ts
server/routes/bookedtoday/summary.test.ts
server/routes/bookedtoday/summary.ts
server/views/components/summary-card.njk
server/views/pages/bookedtoday/summary.njk

Just adding the base components for the new /summary page.
Still need to add in:
- breadcrumbs
- additional data
- integration testing
- wiring up the route into the flow
but this seemed like a neat place to break off 😄

DCS-1932: ✨Add Base Page For `New Arrival Summary Page` Part 1

---

server/utils/nunjucksSetup.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/recentArrivals/recentArrivalsSummary.njk

Body scan summary box as below added to the post arrival summary page:

DCS-2026 add body scan summary box and count to post arrival summary page

---

server/routes/bookedtoday/summaryWithRecordController.test.ts
server/routes/bookedtoday/summaryWithRecordController.ts
server/services/expectedArrivalsService.test.ts
server/services/expectedArrivalsService.ts
server/views/pages/bookedtoday/summaryWithRecord.njk

Body scan summary added to pre arrival single match summary page:

DCS-1937 display body scan count on pre arrival summary page

---

assets/sass/components/_header-bar.scss
server/views/partials/header.njk
server/views/partials/recentArrivalCardMacro.njk

added to prisoner names on /recent-arrivals and the change location in header.

DCS-2016 give links no-visited state

---

integration_tests/integration/bodyscan/bodyScan.cy.ts
integration_tests/pages/bodyscan/bodyScanConfirmation.ts
server/views/pages/bodyscans/scanConfirmation.njk

enable user to navigate from scan confirmation to prisoner summary

DCS-2113 add href to prisoner summary page

---

server/routes/index.ts
server/views/pages/home.njk
server/views/partials/layout.njk

Fix layout changes on home page
localhost 3000 (and so will be dev)
prototype

DCS-2072 correct layout and spacing that was accidentally changed

---

server/views/pages/recentArrivals/recentArrivalsSummary.njk

DCS-2114 change recent arrival summary page tab title

---

server/views/pages/bookedtoday/choosePrisoner.njk
server/views/pages/recentArrivals/recentArrivals.njk
server/views/pages/recentArrivals/recentArrivalsSearch.njk

DCS-2081 heading content update

---

helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml
server/config.ts
server/routes/bookedtoday/summaryWithRecordController.test.ts
server/routes/homeController.test.ts
server/routes/homeController.ts
server/routes/index.ts
server/routes/recentArrivals/recentArrivalsSummaryController.test.ts
server/utils/nunjucksSetup.ts
server/views/components/summary-card.njk
server/views/pages/bookedtoday/summaryWithRecord.njk
server/views/pages/home.njk
server/views/pages/recentArrivals/recentArrivalsSummary.njk

create config var for female prisons and use in view templates

DCS-2232 code refactor

---

server/middleware/setUpWebSecurity.ts

CSP allow list updated as  data not reaching GA4

MAP-34 change CSP to allow list gtm and ga4

---

integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/isSingleMatch.cy.ts
integration_tests/integration/bookedtoday/choosePrisoner.cy.ts
integration_tests/integration/bookedtoday/transfers/transfer.cy.ts
integration_tests/pages/bookedtoday/prisonerSummaryWithRecord.ts
integration_tests/pages/bookedtoday/transfers/summaryTransfer.ts
server/routes/bookedtoday/choosePrisonerController.test.ts
server/routes/bookedtoday/index.ts
server/routes/bookedtoday/summaryMoveOnlyController.ts
server/routes/bookedtoday/summaryWithRecordController.test.ts
server/routes/bookedtoday/summaryWithRecordController.ts
server/routes/bookedtoday/transfers/index.ts
server/routes/bookedtoday/transfers/summaryTransferController.test.ts
server/routes/bookedtoday/transfers/summaryTransferController.ts
server/views/pages/bookedtoday/summaryMoveOnly.njk
server/views/pages/bookedtoday/summaryWithRecord.njk
server/views/pages/bookedtoday/transfers/summaryTransfer.njk
server/views/partials/expectedArrivalCardMacro.njk

*User permissions
*Enable pre arrival summary page on Dev

MAP-113 MVP 2

---

helm_deploy/hmpps-welcome-people-into-prison-ui/Chart.yaml
helm_deploy/hmpps-welcome-people-into-prison-ui/templates/job.yaml

Upgrade Helm chart to be compatible with k8s 1.25
https://dsdmoj.atlassian.net/browse/MAP-343

MAP-343: Upgrade Helm chart to be compatible with k8s 1.25

---

server/@types/welcome/index.d.ts
server/data/__testutils/testObjects.ts
server/middleware/authorisationForUrlMiddleware.ts
server/routes/bookedtoday/choosePrisonerController.test.ts
server/services/__testutils/mocks.ts
server/services/expectedArrivalsService.test.ts
server/services/expectedArrivalsService.ts
server/services/index.ts
server/services/offenceInfoDecorator.test.ts
server/services/offenceInfoDecorator.ts
server/views/components/summary-card.njk
server/views/pages/bookedtoday/summaryMoveOnly.njk

MAP-43-show-offence

---

server/views/partials/layout.njk

Bug caused by new header/footer API ordering issue when compiling the WPIP application. Switched `layout.njk` compilation order to resolve

MAP-481 Bug - Location link

---

package-lock.json
package.json

Minor dependency update

---

package-lock.json
package.json
server/routes/__testutils/requestTestUtils.ts

to fix 
https://github.com/advisories/GHSA-rv95-896h-c2vc
https://github.com/advisories/GHSA-cxjh-pqwp-8mfp

MAP-899 updated dependencies

---

Dockerfile

Reverts ministryofjustice/hmpps-welcome-people-into-prison-ui#461

Revert "MAP-1280 Install postgres cert"

---

package-lock.json
package.json

[MAP-1500](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?quickFilter=3684&selectedIssue=MAP-1500)
[MAP-1500]: https://dsdmoj.atlassian.net/browse/MAP-1500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-1500 update axios to fix CVE

---

package-lock.json
package.json

[MAP-1588](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1588)

MAP-1588 update dev dependency

---

.circleci/config.yml
docker-compose-test.yml

MAP-1624: Switch to official wiremock to match template project

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
package-lock.json
package.json
server/middleware/setUpHealthChecks.ts

This PR is only to update node to v22. Because of this, I have used response type of 'any' in /setUpHealthChecks.ts as temporary a workaround until we align all modules with the template project.
Updates for other dependencies will be in another PR
[See PR in template project that also updates to node 22](https://github.com/ministryofjustice/hmpps-template-typescript/pull/474/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47)

MAP-1859 updated to node v22

---

helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml

Correction 
APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"

MAP-1858 HELM value correction

---

package-lock.json
package.json
server/middleware/authorisationForUrlMiddleware.test.ts
server/routes/__testutils/requestTestUtils.ts
server/utils/state.ts
server/utils/utils.test.ts
server/utils/utils.ts
tsconfig.json

This PR
Upgrade typescript from 4.9.0 to 5.7.2
Lint correction about issues npm run typecheck found.
NOTE: Code has been run locally and created a BASM move to test WPIP-UI. locally

MAP-1858 PR4 aligen typescript version with Template Typescript 

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

https://dsdmoj.atlassian.net/browse/MAP-2035

Add scheduled downtime to non-prod environments

---

package-lock.json
package.json

dependency of cheeiro but cheerio (used for testing) update not available yet

MAP-2434-override-undici

---

.circleci/config.yml

[MAP-2526 ](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?issueParent=391911%2C286167)

MAP-2526 circle-ci orb updated

---

server/middleware/setUpStaticResources.ts
server/views/pages/bodyscans/recordBodyScan.njk
server/views/pages/bookedtoday/arrivals/autoMatchingRecords/multipleMatchingRecordsFound.njk
server/views/pages/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.njk
server/views/pages/unexpectedArrivals/multipleExistingRecordsFound.njk

The fixed pages now look like this
**date picker in body scan:**
**details component in multiple existing records:**

MAP-2673 corrected static imports and html

---

package-lock.json
package.json

[MAP-2669](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?assignee=5cd29c554326200dc971eab7&selectedIssue=MAP-2669)
update cypress
[MAP-2669]: https://dsdmoj.atlassian.net/browse/MAP-2669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MAP-2669 dependency update
