assets/js/googleAnalytics.js, server/middleware/setUpWebSecurity.ts, server/views/partials/layout.njk
Extracted out inline script for google analytics as it was being blocked by the Helmet content security policy middleware. Also added missing content security policy imgSrc directives.
=> DCS-1368 CSP fix to google analytics script

server/views/pages/bookedtoday/arrivals/confirmArrival.njk
'Details from Person Escort Record' is on one line
Discussion with designer confirms the 40/60 column widths are okay
=> DCS-1326 padding removed so that the title 

server/routes/__testutils/appSetup.ts, server/routes/bookedtoday/arrivals/checkAnswersController.test.ts, server/routes/bookedtoday/arrivals/checkAnswersController.ts, server/routes/bookedtoday/arrivals/checkCourtReturnController.test.ts, server/routes/bookedtoday/arrivals/checkCourtReturnController.ts, server/routes/bookedtoday/arrivals/index.ts, server/routes/bookedtoday/transfers/checkTransferController.test.ts, server/routes/bookedtoday/transfers/checkTransferController.ts, server/routes/bookedtoday/transfers/index.ts, server/routes/temporaryabsences/checkTemporaryAbsenceController.test.ts, server/routes/temporaryabsences/checkTemporaryAbsenceController.ts, server/routes/temporaryabsences/index.ts, server/services/index.ts, server/services/raiseAnalyticsEvent.ts
We previously directly imported google analytics event publishing where it is used. Refactored this to avoid use of implicit dependencies.
=> DCS-1408 refactor of raiseAnalyticsEvent

Dockerfile
It looks like CircleCI is always pulling a cache when we run the apt update / upgrade commands, meaning new builds don't pull through the latest versions of packages.
This is an issue since we have security alerts pinging and can't seem to get rid of them.
Not entirely sure on the actual issue here, but the assumption is our Dockerfile is incorrect ( I think maybe having a rm -rf will stop it caching all the commands? ). But I've aligned it more with how the template project does things in hopes that fixes it. Noticed most of our projects build these in different ways, so hard to tell what exactly it is causing the issue.
=> DCS-1445: 🔧 align Dockerfile with template project to discourage circle caching image dependencies

integration_tests/integration/bookedtoday/arrivals/courtreturns/courtReturn.spec.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.test.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.ts, server/routes/bookedtoday/arrivals/sexController.test.ts, server/routes/bookedtoday/arrivals/sexController.ts, server/routes/bookedtoday/transfers/confirmTransferAddedToRollController.test.ts, server/services/expectedArrivalsService.test.ts, server/services/expectedArrivalsService.ts
Now we no longer merge in matching prisoners into the top level arrival
details we fail to show prisoner info on the court return pages.
This fixes that by retrieving the appropriate prisoner record.
It also fixes a minor issue with the sex controller, where if you
navigated through and back again and through the sex controller it
would ask to provide the arrivals sex (even though it initially was
present)
=> DCS-1487 Fix issue with court transfers

integration_tests/pages/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.ts, server/routes/bookedtoday/arrivals/searchforexisting/index.ts, server/routes/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFoundController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFoundController.ts, server/routes/bookedtoday/arrivals/searchforexisting/noExistingRecordsFoundController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/noExistingRecordsFoundController.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.ts, server/routes/bookedtoday/arrivals/searchforexisting/singleExistingRecordFoundController.test.ts, server/views/pages/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.njk, server/views/pages/bookedtoday/arrivals/searchforexisting/noExistingRecordsFound.njk, server/views/pages/bookedtoday/arrivals/searchforexisting/singleExistingRecordFound.njk
Updated no match page content with Personal details subheading for arrival details. We now get these details from state and make sure we only display name and dob:
Updated single match page content with Personal details subheading for arrival details. 
Also updated url path for match result pages which follow the Search for an existing prisoner record page.
=> DCS-1499 corrected search-for-existing-record result pages url paths

server/routes/bookedtoday/arrivals/searchforexisting/search/changeDateOfBirthController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/changeNameController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/changePncNumberController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/changePrisonNumberController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.ts, server/views/pages/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecord.njk
Fixes an issue where if you:
* Search for a record and produce a match
* Select the match and then go through to check your answers you’ll see the details of the match
* If you navigate back to the search page and alter the query so you produce no match
* Confirm this and progress to the check your answer page you will see the old match
=> DCS-1503 clear out new arrival state after no result or multiple results found

integration_tests/integration/bookedtoday/arrivals/isSingleMatch.spec.ts, integration_tests/mockApis/responses/expectedArrivals.ts, server/routes/bookedtoday/arrivals/singleMatchingRecordFoundController.test.ts, server/routes/bookedtoday/arrivals/singleMatchingRecordFoundController.ts
This previously read the value from the arrival rather than the match
This would only affect the display of the sex in the case it differed or wasn't provided by BASM
=> DCS-1504 fix display of sex when single match

server/routes/bookedtoday/unexpectedArrivals/index.ts, server/routes/bookedtoday/unexpectedArrivals/searchForExistingRecordsController.test.ts, server/routes/bookedtoday/unexpectedArrivals/searchForExistingRecordsController.ts, server/routes/bookedtoday/unexpectedArrivals/validation/dateOfBirthValidation.test.ts, server/routes/bookedtoday/unexpectedArrivals/validation/dateOfBirthValidation.ts, server/routes/bookedtoday/unexpectedArrivals/validation/pncNumberValidation.test.ts, server/routes/bookedtoday/unexpectedArrivals/validation/pncNumberValidation.ts, server/routes/bookedtoday/unexpectedArrivals/validation/prisonNumberValidation.test.ts, server/routes/bookedtoday/unexpectedArrivals/validation/prisonNumberValidation.ts, server/routes/bookedtoday/unexpectedArrivals/validation/searchForExistingRecordsValidation.test.ts, server/routes/bookedtoday/unexpectedArrivals/validation/searchForExistingRecordsValidation.ts, server/views/pages/unexpectedArrivals/searchForExistingRecord.njk, server/views/partials/layout.njk
validate user inputs on page /manually-confirm-arrival/search-for-existing-record.
for reference, the validation rules are
- Nothing entered: You must search using either the prisoner's last name, prison number or PNC Number (link to last name field)
- DOB only entered: You must search using either the prisoner's last name, prison number or PNC Number (link to last name field)
- If one or more DOB fields are missing: Date of birth must include a [whatever is missing] and [whatever else is missing]
- First name only entered: Enter a last name (link to last name field)
- Incorrectly formatted prison number: Enter a prison number using 7 characters in the format A1234AA (link to prison number)
- Incorrectly formatted PNC number: Enter a PNC number in the format 01/23456A or 2001/23456A (link …
=> DCS-1467 display input validation errors

integration_tests/integration/bookedtoday/choosePrisoner.spec.ts, integration_tests/pages/bookedtoday/choosePrisoner.ts, server/views/pages/bookedtoday/choosePrisoner.njk
Link takes user /manually-confirm-arrival/search-for-existing-record
Only visible if user has reception role
=> DCS-1466 add link on prisoner search page

integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/hasNoMatchAndPncOnly.spec.ts, server/routes/bookedtoday/arrivals/reviewPerDetailsController.test.ts, server/routes/bookedtoday/arrivals/reviewPerDetailsController.ts
This would only happen if we received an invalid prison number from BASM. We were previously passing it through even though it must have been invalid else we would have received a match
=> DCS-1553 Prevent passing of prison number on new record

server/routes/bookedtoday/unexpectedArrivals/multipleExistingRecordsFoundController.test.ts, server/routes/bookedtoday/unexpectedArrivals/noExistingRecordsFoundController.test.ts, server/routes/bookedtoday/unexpectedArrivals/singleExistingRecordFoundController.test.ts, server/views/components/prisoner-search-detail.njk, server/views/pages/unexpectedArrivals/multipleExistingRecordsFound.njk, server/views/pages/unexpectedArrivals/noExistingRecordsFound.njk, server/views/pages/unexpectedArrivals/singleExistingRecordFound.njk
If either of prisoner name, dob, prison number, pnc are not provided in search the text 'Not entered' will be displayed.
If the first name is not provided but last name is, then first name will not be displayed. 
Previously the above missing criteria would result in the ui displaying 'undefined'
=> DCS-1541 handle display of prisoner search details

server/routes/bookedtoday/unexpectedArrivals/validation/searchForExistingRecordsValidation.test.ts, server/routes/bookedtoday/unexpectedArrivals/validation/searchForExistingRecordsValidation.ts
Validation prevents a search when either first name or dob are present but last name is missing.
This also means, the last name will not be displayed as 'undefined' in the search results page
=> DCS-1574 validation for missing last name

server/data/welcomeClient.test.ts, server/data/welcomeClient.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.test.ts, server/services/expectedArrivalsService.test.ts, server/services/expectedArrivalsService.ts
a status code between  400 and 500 from welcomeApi determines the redirect to /feature-not-available.
This PR is for court returns journey only.
=> DCS-1581 welcomeApi client errors return null or throw error

server/data/welcomeClient.test.ts, server/data/welcomeClient.ts, server/routes/bookedtoday/transfers/checkTransferController.test.ts, server/routes/bookedtoday/transfers/checkTransferController.ts, server/services/transfersService.test.ts, server/services/transfersService.ts
400-500 client errors when calling welcome-api will cause null to be returned to the controller which which will then redirect to /feature-not-available
=> DCS-1581 handle client errors for transfers

helm_deploy/hmpps-welcome-people-into-prison-ui/Chart.yaml, helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Dev and Preprod to digital-prison-service-dev.
Prod to elp_alerts.
Latest version of generic-proetheus-alerts is 0.4.1, see https://github.com/ministryofjustice/hmpps-helm-charts/releases?page=1
=> DCS-1081 prometheus alerts for prod to elp_alerts slack channel

server/config.ts, server/data/healthCheck.test.ts, server/data/restClient.ts, server/data/welcomeClient.ts
Disabling retries and extending timeouts so we don’t batter BASM as much when they’re having perf issues. 
Also means patient users are more likely to see results quicker!
=> DCS-1651 Extending timeouts to calls for pages displaying lists and disabling retries

server/views/pages/bodyscans/scanConfirmation.njk
Small css fix to add more space between banner and Add more information about this body scan h2:
From
To
=> DCS-1686 body scan confirmation page css fix

integration_tests/pages/bodyscan/bodyScanConfirmation.ts, integration_tests/pages/bookedtoday/arrivals/confirmArrival/confirmAddedToRoll.ts, integration_tests/pages/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.ts, integration_tests/pages/bookedtoday/transfers/confirmTransferAddedToRoll.ts, integration_tests/pages/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.ts, server/views/pages/bodyscans/scanConfirmation.njk, server/views/pages/bookedtoday/arrivals/confirmArrival/confirmAddedToRoll.njk, server/views/pages/bookedtoday/arrivals/courtreturns/confirmCourtReturnAddedToRoll.njk, server/views/pages/bookedtoday/transfers/confirmTransferAddedToRoll.njk, server/views/pages/temporaryabsences/confirmTemporaryAbsenceAddedToRoll.njk
PR to update the **Add a case note** link to use the DPS backlink URL so users aren't dead-ended after adding a case note.
There are essentially only two link updates here
- Update Temporary Absence Confirmation so the return URL is **/**
- Update every other Confirmation Page so the return URL is **/confirm-arrival/choose-prisoner**
Apologies for the mass indentations, seems like our standard is four indents hadn't been applied in some instances 👀 I'd recommend hiding whitespace changes in Github to see the actual changes in the .njk files😄
=> DCS-1691: ♻️ Move to using DPS backlink endpoint for Case Notes

server/data/__testutils/testObjects.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/multipleMatchingRecordsFoundController.test.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/noMatchingRecordsFoundController.test.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/singleMatchingRecordFoundController.test.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.test.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.test.ts, server/routes/bookedtoday/choosePrisonerController.test.ts, server/routes/bookedtoday/choosePrisonerController.ts, server/routes/recentArrivals/recentArrivalsController.test.ts, server/services/__testutils/mocks.ts, server/services/expectedArrivalsService.test.ts, server/services/expectedArrivalsService.ts, server/services/index.ts, server/services/matchTypeDecorator.test.ts, server/services/matchTypeDecorator.ts
Now decorating incoming arrivals with information about the type of match we have been able to work out for an arrival.
There are 4 possible options, 3 self evident: 
```
SINGLE_MATCH
NO_MATCH
MULTIPLE_POTENTIAL_MATCHES
```
And a special option of `INSUFFICIENT_INFO` for when we haven't been provided a PNC or prisoner number. In this case we don't entirely trust a name and Dob match.
This additional data, slightly simplifies the routing logic when working out how to process a prisoner. We will also use this info to work out whether to show a photo.
We currently always show the photo associated with the first potential match which can be a bit confusing for multiple matches and when we have insufficient data
=> DCS-1786 extracting out logic around deriving match type

package-lock.json, package.json, server.ts, server/config.ts, server/index.ts, server/utils/azureAppInsights.ts
Moving dotenv to dev dependencies. This removes some code that is only relevant for local development. This code was a bit tricky as it required running at a specific time in the application lifecycle.
There was a weird bug where the app insight initialise() would fail if the env vars weren't present before the app insights import.
This now means the application runs similar locally to how it would run in docker or kubernetes.
Also moving the app insights import so it's very obviously the first thing that happens when the app starts.
=> DCS-1852 Move dotenv to dev dependencies

server/routes/bookedtoday/arrivals/confirmArrival/startConfirmationController.test.ts, server/routes/bookedtoday/arrivals/confirmArrival/startConfirmationController.ts
- When searching for an unexpected arrival a user may find a single matched record
- This record could marked as out on a court visit
- When the user tries to continue against this record, rather than route to the confirm arrival steps the service recognises the record as coming back from court and routes the user to the court return booking flow
- This route results in failure 
We have another ticket to properly address the problem described above. This is a short term fix to redirect court returns to feature-not-available page after we “resolve arrival type”, see [image](https://app.diagrams.net/?title=rejig-resolution&client=1#G1WnwY4nO0jY4owlsXXSf_AAXt4H3zF-YI) 
The existing court return flow, after you select a prisoner from the choose prisoner page still exists.
=> DCS-1857 redirect court flow to feature not available as short term fix for redirect to court flow

server/routes/__testutils/requestTestUtils.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.test.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.ts, server/routes/bookedtoday/choosePrisonerController.test.ts, server/routes/bookedtoday/choosePrisonerController.ts
If there is a record with no identifiers, and a user makes changes on the search for existing page (e.g. adds an identifier for an existing prisoner and changes the DoB). When they click search they should see the single match page with the search details on the left and the found record on the right.
If they choose to create a new record then they will see the details of the original arrival (with original DoB) on the review details page rather than the searched DoB.
This change will prioritise looking at the search details before loading the current arrival so that a user will end up seeing these on the review details page if present.
=> DCS-1859 check for search details cookie on review details page

integration_tests/mockApis/welcome.ts, server/data/welcomeClient.test.ts, server/data/welcomeClient.ts, server/routes/temporaryabsences/checkTemporaryAbsenceController.test.ts, server/routes/temporaryabsences/checkTemporaryAbsenceController.ts, server/services/temporaryAbsencesService.test.ts, server/services/temporaryAbsencesService.ts
Update to the getTemporaryAbsence endpoint in the frontend following update of this endpoint in the backend. 
This was done so that the service does not blow up when a user redirects an arrival to a temporary absence from another prison (which can occur if they search for an arrival with an identifier of a temporary absence from another prison).
Previously the endpoint would not be able to retrieve this temporary absence (as it searched using the agencyId of the user's current active caseload rather than that of the temporary absence) and cause the service to fail on the check temporary absence page. 
Now a user can redirect to this page and view the temporary absence information for temporary absences from another prison, but if they try to confirm the backend will throw an exception and …
=> DCS-1877 update get temporary absence endpoint following endpoint update for fix in backend

.circleci/config.yml, server/routes/bookedtoday/arrivals/reviewDetailsController.test.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.ts
Bug fix to populate new arrival cookie state from search details in search for existing journey. When a user cannot find an arrival match and clicks the create a new record link on the single match or multiple match page: 
This link redirects to `/review-per-details/new` which clears out pre-existing new arrival state, however this does need to be repopulated from search details as when a user continues on from the review page the prison number is deconstructed from the new arrival state as the `start-confirmation` controller redirects to the relevant new arrival confirmation journey.
=> DCS-1983 create new record bug fix

server/views/pages/serviceUnavailable.njk
Changed the style of the DPS back link in the service unavailable page to 
This change is on top of Michal's change that sets the SERVICE_IS_UNAVAILABLE to true for prod
=> DCS-2001 change style of DPS link

assets/sass/components/_compliance-panel.scss, server/views/pages/bookedtoday/summaryWithRecord.njk
Added red over body scan limit warning to pre arrival summary page as below. This only displays when a person has reached 116+ body scans:
=> DCS-2008 add over body scan limit warning to pre arrival summery page

server/views/pages/recentArrivals/recentArrivalsSummary.njk
Added red over body scan limit warning to post arrival summary page as below. This only displays when a person has reached 116+ body scans:
=> DCS-2009 add over body scan limit warning to post arrival summary page

server/authentication/role.ts, server/routes/bookedtoday/index.ts, server/routes/bookedtoday/summaryWithRecordController.test.ts, server/routes/bookedtoday/summaryWithRecordController.ts, server/views/pages/bookedtoday/summaryWithRecord.njk
Button added to enable user to access prisoner profile  in DPS from wpip-ui pre-arrival prisoner summary page. 
User needs the “Reception user“ and “Released Prisoner Viewing” roles to see button
Verified role mappings with HAAR Team member
Reception Staff -> ROLE_PRISON_RECEPTION
Released Prisoner Viewing -> ROLE_INACTIVE_BOOKINGS
=> DCS-1927 add link pointing to prisoner profile on dps

server/routes/recentArrivals/index.ts, server/views/pages/recentArrivals/recentArrivalsSummary.njk
The save-backlink endpoint automatically creates a link in DPS enabling user to return to the summary page
=> DCS-1948 add button enabling user to view prisoner profile in DPS

integration_tests/integration/bodyscan/bodyScan.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/hasMultipleMatches.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/hasNoMatchAndPncOnly.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/isSingleMatch.cy.ts, integration_tests/integration/bookedtoday/arrivals/courtreturns/courtReturn.cy.ts, integration_tests/integration/bookedtoday/arrivals/resolvingTypesOfArrivals.cy.ts, integration_tests/integration/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.cy.ts, integration_tests/integration/bookedtoday/arrivals/searchforexisting/searchForExisting.cy.ts, integration_tests/integration/bookedtoday/choosePrisoner.cy.ts, integration_tests/integration/bookedtoday/transfers/transfer.cy.ts, integration_tests/integration/bookedtoday/unexpectedArrivals/multipleMatchingRecordsFound.cy.ts, integration_tests/integration/bookedtoday/unexpectedArrivals/noMatchRecord.cy.ts, integration_tests/integration/bookedtoday/unexpectedArrivals/singleMatchRecord.cy.ts, integration_tests/integration/featureNotAvailable.cy.ts, integration_tests/integration/feedback.cy.ts, integration_tests/integration/homePage.cy.ts, integration_tests/integration/login.cy.ts, integration_tests/integration/recentArrivals/recentArrivals.cy.ts, integration_tests/integration/temporaryabsences/temporaryAbsence.cy.ts, integration_tests/integration/temporaryabsences/temporaryAbsences.cy.ts, integration_tests/mockApis/auth.ts
need to add multiple roles as the dpslink from pre-arrival prsioner summary has a button to the DPS profile and the button should show only if user has the two required roles
=> DCS-1799 integration tests can stub multiple user roles

integration_tests/integration/bodyscan/bodyScan.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/hasMultipleMatches.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/hasNoMatchAndPncOnly.cy.ts, integration_tests/integration/bookedtoday/arrivals/autoMatchingRecords/isSingleMatch.cy.ts, integration_tests/integration/bookedtoday/arrivals/courtreturns/courtReturn.cy.ts, integration_tests/integration/bookedtoday/arrivals/resolvingTypesOfArrivals.cy.ts, integration_tests/integration/bookedtoday/arrivals/searchforexisting/multipleExistingRecordsFound.cy.ts, integration_tests/integration/bookedtoday/arrivals/searchforexisting/searchForExisting.cy.ts, integration_tests/integration/bookedtoday/choosePrisoner.cy.ts, integration_tests/integration/featureNotAvailable.cy.ts, integration_tests/integration/recentArrivals/recentArrivals.cy.ts, integration_tests/mockApis/auth.ts, integration_tests/mockApis/responses/bodyScans.ts, integration_tests/mockApis/welcome.ts, integration_tests/pages/bookedtoday/choosePrisoner.ts, integration_tests/pages/bookedtoday/prisonerSummaryMoveOnly.ts, integration_tests/pages/bookedtoday/prisonerSummaryWithRecord.ts, server/routes/bookedtoday/index.ts, server/routes/bookedtoday/summaryController.test.ts, server/routes/bookedtoday/summaryController.ts, server/routes/bookedtoday/summaryWithRecordController.test.ts, server/views/pages/bookedtoday/summaryMoveOnly.njk, server/views/pages/bookedtoday/summaryWithRecord.njk, server/views/partials/expectedArrivalCardMacro.njk
Feature: when user clicks on a prisoner's name in the arrival list then one of two possible summary pages are displayed before the journey resumes to the original result set page. 
court returns, single matches  -> summaryWithRecord
multi-match, no-match, no ids ->  summaryMoveOnly
=> Dcs 1799 wpip UI add links from arrivals page to person summary

server/data/lockManager.test.ts, server/data/lockManager.ts, server/middleware/backTrackPreventionMiddleware.test.ts, server/middleware/backTrackPreventionMiddleware.ts, server/routes/bookedtoday/arrivals/confirmArrival/checkAnswersController.test.ts, server/routes/bookedtoday/arrivals/confirmArrival/checkAnswersController.ts, server/routes/bookedtoday/arrivals/confirmArrival/index.ts
This v2 is as a result of issues found following peer testing. please refer to Charan's notes of 18/4 in the jira ticket.
There are two changes in this PR
1. In the unexpected-arrivals journey we don't want the double booking error page to be shown. 
The functionality has been achieved in the backtracking prevention middleware which only sets the lock if the 'id' in the url is not 'unexpected-arrival' 
2. In the standard expected arrival journey, if the user attempts to backtrack from 'Feature not available' page then we do not want to display the 'This person is being booked in' page.
This functionality has been achieved by calling the deleteLock function in the post to checkAnswersController if the application did not successfully confirm the arrival. (note: the rendering of the 'This …
=> DCS 2079 wpip UI prevent arrival reconfirmation v2

server/routes/bookedtoday/arrivals/autoMatchingRecords/multipleMatchingRecordsFoundController.test.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/multipleMatchingRecordsFoundController.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/noMatchingRecordsFoundController.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/singleMatchingRecordFoundController.test.ts, server/routes/bookedtoday/arrivals/autoMatchingRecords/singleMatchingRecordFoundController.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.test.ts, server/routes/bookedtoday/arrivals/courtreturns/checkCourtReturnController.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.test.ts, server/routes/bookedtoday/arrivals/reviewDetailsController.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.test.ts, server/routes/bookedtoday/arrivals/searchforexisting/search/searchForExistingRecordController.ts, server/routes/bookedtoday/choosePrisonerController.test.ts, server/routes/bookedtoday/choosePrisonerController.ts, server/routes/bookedtoday/summaryController.test.ts, server/routes/bookedtoday/summaryController.ts, server/routes/bookedtoday/summaryMoveOnlyController.test.ts, server/routes/bookedtoday/summaryMoveOnlyController.ts, server/routes/bookedtoday/summaryWithRecordController.test.ts, server/routes/bookedtoday/summaryWithRecordController.ts, server/services/expectedArrivalsService.test.ts, server/services/expectedArrivalsService.ts
The BASM service would like to know which users access its service. This will be achieved by adding the 'X-current-user' header to calls made by wpip-api to BASM. However the user details originate in wpip-ui and hence they need to be passed from wpip-ui to wpip-api and onwards to BASM.
There are 2 specific wpip-api endpoints that need the username:- 
1. /arrivals/{arrivalId}
2. /prisons/{prisonId}/arrivals
So this ticket is to add the username to wpip-ui functions that result in hitting those 2 endpoints.
=> DCS-2145 send username to backend for some calls

server/routes/bookedtoday/choosePrisonerController.test.ts, server/routes/bookedtoday/summaryMoveOnlyController.test.ts, server/routes/bookedtoday/summaryWithRecordController.test.ts, server/routes/bookedtoday/transfers/summaryTransferController.test.ts, server/routes/recentArrivals/recentArrivalsController.test.ts, server/routes/recentArrivals/recentArrivalsSummaryController.test.ts, server/routes/temporaryabsences/checkTemporaryAbsenceController.test.ts, server/views/pages/bookedtoday/choosePrisoner.njk, server/views/pages/recentArrivals/recentArrivalsSummary.njk, server/views/pages/temporaryabsences/temporaryAbsences.njk, server/views/partials/breadCrumb.njk, server/views/partials/layout.njk
change format of breadcrumbs in following pages
/choose-prisoner
prisoners-returning
/recent-arrivals/
/recent-arrivals/UUID/summary
/summary-move-only
/summary-with-record
so that 
the first link in the trail should is 'Digital Prison Services' which will take users back to the DPS homepage
second link will be Welcome people into prison i.e  Digital Prison Services > Welcome people into prison
the last crumb is the penultimate page visited.
the current page is not included in the breadcrumb trail
=> MAP-245 change breadcrumb format

server/middleware/setUpWebSecurity.ts
Requires scriptSrc to include 'self'  - missed in previous PR
was preventing back link from working
=> MAP-302 add missing target for scripts in helmet

.circleci/config.yml, helm_deploy/hmpps-welcome-people-into-prison-ui/Chart.yaml, helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons,private_prisons`
- The size of the allowlist defined in this file will change: `54 => 0 (54 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
Merging this PR should not result in any additional IP addresses being added to the allowlist. …
=> Migrating project to use groups in allowlist

package-lock.json, package.json
'follow-redirects' has a CVE vulnerability.  
It is a 2nd level dependency of notifications-node-client. Updating notifications-node-client on it's own did not result in update of follow-redirect. So overrode  axios to 1.6.7 as this  uses follow-redirects
dependency tree: 
notifications-node-client@8.0.0
axios@1.6.7
follow-redirects@1.15.5
form-data@4.0.0 deduped
proxy-from-env@1.1.0
see https://www.npmjs.com/package/notifications-node-client?activeTab=dependencies
=> MAP-828 fix CVE vulnerability

jobs/eventsJob.ts, jobs/eventsPusher.ts, jobs/eventsRetriever.test.ts, jobs/eventsRetriever.ts
[MAP-1560](https://dsdmoj.atlassian.net/jira/software/c/projects/MAP/boards/1354?selectedIssue=MAP-1560)
[This](https://mojdt.slack.com/archives/C03DBE9GNJE/p1724069540080749) cron job failing because the data being pushed to the google sheet was exceeding the sheet's limits. This is because new data is appended to existing data , which began in 2021. The change in this code is to replace rather than append data,  and limit it to a rolling 1 year back in time. 
[MAP-1560]: https://dsdmoj.atlassian.net/browse/MAP-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-1560 google sheets limited to 1 year of data

helm_deploy/hmpps-welcome-people-into-prison-ui/Chart.yaml, helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml
Updated HELM charts.yml to {bellow} following Template Typescript repo & generic-prometheus-alerts set up 
version: "3.6"
version: "1.10"
As UOF API and LOCA UI have these versions already testd.
Template Typescript is using 3.7 and 1.11.
=> Map 1858 template typescript merge

helm_deploy/hmpps-welcome-people-into-prison-ui/values.yaml
After investigation it has been revealed that deployment claimed about the new APPINSIGHTS_INSTRUMENTATIONKEY resetting as it need some extra change out of the box.
=> MAP-1858 HELM upgrade 3.6 and fix to build it

jobs/eventsJob.ts, jobs/eventsRetriever.test.ts, jobs/eventsRetriever.ts
Job for the Looker  Studio report crashes because it takes too long to create a report. We are currently getting 1 years worth of the data. Reducing that to 6 months to see if that stops the crash
=> MAP-2071 reduced the data capture to last 6 months
